#!/usr/bin/env bash
# Install tmux from nelsonenzo/tmux-appimage static build.
# AppImage is extracted (--appimage-extract) so FUSE is not required —
# HPC compute nodes typically disable FUSE.
set -euo pipefail

VERSION="3.5a"
LOCAL_BIN="$HOME/.local/bin"
SOFTWARE="$HOME/software/tmux"
APPDIR="$SOFTWARE/squashfs-root"
INNER="$APPDIR/usr/bin/tmux"
WRAPPER_MARKER="dotfiles-tmux-appimage-wrapper"

# The AppImage bundles its own libncurses (RUNPATH $ORIGIN/../lib) whose
# compiled-in terminfo default is /opt/build/AppDir/usr/share/terminfo — a path
# that only ever existed on the AppImage build machine — with no fallback list.
# Symlinking straight to the inner binary therefore aborts every command that
# needs a terminal ("missing or unsuitable terminal: $TERM"). Upstream's AppRun
# exports TERMINFO; this wrapper does the same, host database first so host-only
# entries (e.g. xterm-kitty under ~/.terminfo) keep resolving.
write_wrapper() {
    mkdir -p "$LOCAL_BIN"
    rm -f "$LOCAL_BIN/tmux"
    cat > "$LOCAL_BIN/tmux" <<'WRAPPER'
#!/usr/bin/env bash
# dotfiles-tmux-appimage-wrapper — generated by dotfiles/install/install-tmux.sh
#
# The bundled libncurses looks for terminfo under the AppImage build machine's
# /opt/build/AppDir/usr/share/terminfo and has no fallback list, so without
# TERMINFO_DIRS tmux dies with "missing or unsuitable terminal: $TERM" on any
# command that needs a terminal (new-session, attach, and every client command
# run with a tty on stdin). Point it at the host database instead.
__APPDIR__="@APPDIR@"
export TERMINFO_DIRS="${TERMINFO_DIRS:+$TERMINFO_DIRS:}$HOME/.terminfo:/etc/terminfo:/usr/share/terminfo:/lib/terminfo:${__APPDIR__}/usr/share/terminfo"
exec "${__APPDIR__}/usr/bin/tmux" "$@"
WRAPPER
    sed -i "s|@APPDIR@|$APPDIR|" "$LOCAL_BIN/tmux"
    chmod +x "$LOCAL_BIN/tmux"
}

if [[ -x "$INNER" ]]; then
    if grep -q "$WRAPPER_MARKER" "$LOCAL_BIN/tmux" 2>/dev/null; then
        echo "✓ tmux already installed: $LOCAL_BIN/tmux ($("$LOCAL_BIN/tmux" -V))"
    else
        # Older installs symlinked the inner binary directly — repair in place.
        write_wrapper
        echo "✓ tmux wrapper repaired: $LOCAL_BIN/tmux ($("$LOCAL_BIN/tmux" -V))"
    fi
    exit 0
fi

arch="$(uname -m)"
case "$arch" in
    x86_64) ;;
    aarch64|arm64)
        echo "✗ tmux-appimage has no arm64 build."
        echo "  Install via your cluster's package manager, or:"
        echo "    micromamba install -n base -c conda-forge tmux"
        exit 1
        ;;
    *) echo "✗ unsupported arch: $arch"; exit 1 ;;
esac

mkdir -p "$SOFTWARE" "$LOCAL_BIN"
cd "$SOFTWARE"

url="https://github.com/nelsonenzo/tmux-appimage/releases/download/${VERSION}/tmux.appimage"
echo "→ fetching tmux $VERSION AppImage"
curl -fsSL -o tmux.appimage "$url"
chmod +x tmux.appimage

# Extract: FUSE is unavailable on most cluster compute nodes.
rm -rf squashfs-root
./tmux.appimage --appimage-extract >/dev/null
rm -f tmux.appimage

if [[ ! -x "$INNER" ]]; then
    echo "✗ extracted AppImage missing $INNER"
    exit 1
fi

write_wrapper
echo "✓ tmux installed: $("$LOCAL_BIN/tmux" -V)"
